In [1]:
import numpy as np

In [ ]:
#Уровень 0:
#Задание 1




#Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [2]:
#Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Прибавьте к ней матрицу с единицами на диагонале
A2 = np.eye(3, 3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
A3 = A1 + A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [11]:
#Умножьте полученную матрицу на вектор (1, 2, 3)
F = np.array([1, 2, 3])
A4 = A3@F


In [12]:
A4

array([15., 34., 53.])

In [14]:
#Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
A5 = np.transpose(A3)
A5

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [15]:
#Посчитайте обратную матрицу к полученной в результате прибавления матрице
A6 = np.linalg.inv(A3)
A6






array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [16]:
A3@A6 # матрица A3 не имеет обратной матрицы

array([[ 1.00000000e+00, -2.22044605e-16,  4.44089210e-16],
       [-1.77635684e-15,  1.00000000e+00,  8.88178420e-16],
       [-1.77635684e-15,  4.44089210e-16,  1.00000000e+00]])

In [17]:
#Уровень 1:
#Задание 2
#Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [18]:
np.linalg.eig(m) #собственные значения и собственные вектора

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [20]:
np.linalg.eigvals(m) #только собственные значения

array([1., 4.])

In [22]:
#Задание 3
#Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

#P.S. Матрица должна быть ненулевой и размерностью не менее 2!
m1 = np.array([[2, 1], [1, 1]])
m1

array([[2, 1],
       [1, 1]])

In [24]:
np.linalg.det(m1)

1.0